# build command :
#   cat Dockerfile-MySQL | docker build -t yuanmomo/webase-mysql:1.3.2 -f - https://github.com/WeBankFinTech/WeBASE-Node-Manager.git#dev131
#

FROM mysql:5.7
LABEL maintainer yuanhongbin9090@gmail.com

WORKDIR /code

# copy source code
COPY script/*.sql /docker-entrypoint-initdb.d/